//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/UiControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UiControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UiControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UiControls"",
    ""maps"": [
        {
            ""name"": ""GameSceneMap"",
            ""id"": ""522b72aa-178f-4ebd-9bfb-963d595ab01b"",
            ""actions"": [
                {
                    ""name"": ""ToggleOptions"",
                    ""type"": ""Button"",
                    ""id"": ""a9d3804d-422f-4373-af02-e4c15bfffe44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EscPressed"",
                    ""type"": ""Button"",
                    ""id"": ""bc1fcc5d-27c3-46ca-a830-5bffb516a489"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleCraftingMenu"",
                    ""type"": ""Button"",
                    ""id"": ""7ca1e8ee-4eae-4ad0-ae78-918e674eb5ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""39f15204-3011-4ff8-9ce2-babd12868196"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleOptions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""659198a6-6442-4d28-8029-42897fcfb9d0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""651ef646-3d49-440b-a3f1-955d8ca9cc93"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCraftingMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ObjectPlacementMap"",
            ""id"": ""8910d009-3840-43c9-b1fd-b4439044e8e6"",
            ""actions"": [
                {
                    ""name"": ""PlaceObject"",
                    ""type"": ""Button"",
                    ""id"": ""db84f024-cd5c-4d22-afe7-f0fefc314757"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4a323fb-a435-4c37-adea-394e8734b991"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameSceneMap
        m_GameSceneMap = asset.FindActionMap("GameSceneMap", throwIfNotFound: true);
        m_GameSceneMap_ToggleOptions = m_GameSceneMap.FindAction("ToggleOptions", throwIfNotFound: true);
        m_GameSceneMap_EscPressed = m_GameSceneMap.FindAction("EscPressed", throwIfNotFound: true);
        m_GameSceneMap_ToggleCraftingMenu = m_GameSceneMap.FindAction("ToggleCraftingMenu", throwIfNotFound: true);
        // ObjectPlacementMap
        m_ObjectPlacementMap = asset.FindActionMap("ObjectPlacementMap", throwIfNotFound: true);
        m_ObjectPlacementMap_PlaceObject = m_ObjectPlacementMap.FindAction("PlaceObject", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameSceneMap
    private readonly InputActionMap m_GameSceneMap;
    private List<IGameSceneMapActions> m_GameSceneMapActionsCallbackInterfaces = new List<IGameSceneMapActions>();
    private readonly InputAction m_GameSceneMap_ToggleOptions;
    private readonly InputAction m_GameSceneMap_EscPressed;
    private readonly InputAction m_GameSceneMap_ToggleCraftingMenu;
    public struct GameSceneMapActions
    {
        private @UiControls m_Wrapper;
        public GameSceneMapActions(@UiControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleOptions => m_Wrapper.m_GameSceneMap_ToggleOptions;
        public InputAction @EscPressed => m_Wrapper.m_GameSceneMap_EscPressed;
        public InputAction @ToggleCraftingMenu => m_Wrapper.m_GameSceneMap_ToggleCraftingMenu;
        public InputActionMap Get() { return m_Wrapper.m_GameSceneMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameSceneMapActions set) { return set.Get(); }
        public void AddCallbacks(IGameSceneMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Add(instance);
            @ToggleOptions.started += instance.OnToggleOptions;
            @ToggleOptions.performed += instance.OnToggleOptions;
            @ToggleOptions.canceled += instance.OnToggleOptions;
            @EscPressed.started += instance.OnEscPressed;
            @EscPressed.performed += instance.OnEscPressed;
            @EscPressed.canceled += instance.OnEscPressed;
            @ToggleCraftingMenu.started += instance.OnToggleCraftingMenu;
            @ToggleCraftingMenu.performed += instance.OnToggleCraftingMenu;
            @ToggleCraftingMenu.canceled += instance.OnToggleCraftingMenu;
        }

        private void UnregisterCallbacks(IGameSceneMapActions instance)
        {
            @ToggleOptions.started -= instance.OnToggleOptions;
            @ToggleOptions.performed -= instance.OnToggleOptions;
            @ToggleOptions.canceled -= instance.OnToggleOptions;
            @EscPressed.started -= instance.OnEscPressed;
            @EscPressed.performed -= instance.OnEscPressed;
            @EscPressed.canceled -= instance.OnEscPressed;
            @ToggleCraftingMenu.started -= instance.OnToggleCraftingMenu;
            @ToggleCraftingMenu.performed -= instance.OnToggleCraftingMenu;
            @ToggleCraftingMenu.canceled -= instance.OnToggleCraftingMenu;
        }

        public void RemoveCallbacks(IGameSceneMapActions instance)
        {
            if (m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameSceneMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GameSceneMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameSceneMapActions @GameSceneMap => new GameSceneMapActions(this);

    // ObjectPlacementMap
    private readonly InputActionMap m_ObjectPlacementMap;
    private List<IObjectPlacementMapActions> m_ObjectPlacementMapActionsCallbackInterfaces = new List<IObjectPlacementMapActions>();
    private readonly InputAction m_ObjectPlacementMap_PlaceObject;
    public struct ObjectPlacementMapActions
    {
        private @UiControls m_Wrapper;
        public ObjectPlacementMapActions(@UiControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlaceObject => m_Wrapper.m_ObjectPlacementMap_PlaceObject;
        public InputActionMap Get() { return m_Wrapper.m_ObjectPlacementMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ObjectPlacementMapActions set) { return set.Get(); }
        public void AddCallbacks(IObjectPlacementMapActions instance)
        {
            if (instance == null || m_Wrapper.m_ObjectPlacementMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ObjectPlacementMapActionsCallbackInterfaces.Add(instance);
            @PlaceObject.started += instance.OnPlaceObject;
            @PlaceObject.performed += instance.OnPlaceObject;
            @PlaceObject.canceled += instance.OnPlaceObject;
        }

        private void UnregisterCallbacks(IObjectPlacementMapActions instance)
        {
            @PlaceObject.started -= instance.OnPlaceObject;
            @PlaceObject.performed -= instance.OnPlaceObject;
            @PlaceObject.canceled -= instance.OnPlaceObject;
        }

        public void RemoveCallbacks(IObjectPlacementMapActions instance)
        {
            if (m_Wrapper.m_ObjectPlacementMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IObjectPlacementMapActions instance)
        {
            foreach (var item in m_Wrapper.m_ObjectPlacementMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ObjectPlacementMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ObjectPlacementMapActions @ObjectPlacementMap => new ObjectPlacementMapActions(this);
    public interface IGameSceneMapActions
    {
        void OnToggleOptions(InputAction.CallbackContext context);
        void OnEscPressed(InputAction.CallbackContext context);
        void OnToggleCraftingMenu(InputAction.CallbackContext context);
    }
    public interface IObjectPlacementMapActions
    {
        void OnPlaceObject(InputAction.CallbackContext context);
    }
}
