//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/UiControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UiControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UiControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UiControls"",
    ""maps"": [
        {
            ""name"": ""GameSceneMap"",
            ""id"": ""522b72aa-178f-4ebd-9bfb-963d595ab01b"",
            ""actions"": [
                {
                    ""name"": ""ToggleOptions"",
                    ""type"": ""Button"",
                    ""id"": ""a9d3804d-422f-4373-af02-e4c15bfffe44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""39f15204-3011-4ff8-9ce2-babd12868196"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleOptions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameSceneMap
        m_GameSceneMap = asset.FindActionMap("GameSceneMap", throwIfNotFound: true);
        m_GameSceneMap_ToggleOptions = m_GameSceneMap.FindAction("ToggleOptions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameSceneMap
    private readonly InputActionMap m_GameSceneMap;
    private List<IGameSceneMapActions> m_GameSceneMapActionsCallbackInterfaces = new List<IGameSceneMapActions>();
    private readonly InputAction m_GameSceneMap_ToggleOptions;
    public struct GameSceneMapActions
    {
        private @UiControls m_Wrapper;
        public GameSceneMapActions(@UiControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleOptions => m_Wrapper.m_GameSceneMap_ToggleOptions;
        public InputActionMap Get() { return m_Wrapper.m_GameSceneMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameSceneMapActions set) { return set.Get(); }
        public void AddCallbacks(IGameSceneMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Add(instance);
            @ToggleOptions.started += instance.OnToggleOptions;
            @ToggleOptions.performed += instance.OnToggleOptions;
            @ToggleOptions.canceled += instance.OnToggleOptions;
        }

        private void UnregisterCallbacks(IGameSceneMapActions instance)
        {
            @ToggleOptions.started -= instance.OnToggleOptions;
            @ToggleOptions.performed -= instance.OnToggleOptions;
            @ToggleOptions.canceled -= instance.OnToggleOptions;
        }

        public void RemoveCallbacks(IGameSceneMapActions instance)
        {
            if (m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameSceneMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GameSceneMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameSceneMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameSceneMapActions @GameSceneMap => new GameSceneMapActions(this);
    public interface IGameSceneMapActions
    {
        void OnToggleOptions(InputAction.CallbackContext context);
    }
}
