    public enum MainLibrarySounds {
        BobSplash,
        BobSplashHeavy,
        BobSplashLight,
        BobSplashNormal,
        CastRod,
        CastRodWhoosh,
        CastRodWhooshLight,
        FishHooked,
        FishOnHookNormal,
        FishSplashSmall,
        ReelFishHooked,
        ReelFishShort,
        ItemDrop,
        ItemPickup,
        ConfirmTick,
        DialogueNext,
        SelectSuppressed,
        WoodenTick,
        InventoryFull,
        PlaceStructure,
        InvalidPlacement,
        TreeDestroy_01,
        TreeDestroy_02,
        FistHitTree_01,
        FistHitTree_02
    }
    public enum MainLibraryMusic {
    }
